- name: Get instances detail
  ec2_instance_info:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    region: "{{ region }}"
  register: result

- name: Show Instances ID
  debug:
    msg: "Tags Name : {{ item.tags.Name }} ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
  loop: "{{ result.instances }}"