- name: Terminate EC2 instances
  ec2:
    region: "{{ region }}"
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    state: 'absent'
    instance_id: "{{ item.instance_id }}"
  loop: "{{ result.instances }}"    
  when: item.tags.Name == instance_tag